apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: global-search
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: global
    spec:
      containers:
        - name: global
          image: gcr.io/gcp-brightlab/amar-poc/image_to_be_replace
          volumeMounts: 
          - mountPath: /global-logs
            name: global-vol
          ports:
            - containerPort: 8000
      volumes:
        - name: global-vol
          persistentVolumeClaim:
            claimName: global-claim
