apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: global-claim
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi