apiVersion: v1
kind: PersistentVolume
metadata:
  name: global-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: global-claim
  gcePersistentDisk:
    pdName: jenkins-test