apiVersion: v1
kind: Service
metadata:
  name: global-search-service
  labels:
    name: global-search-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: global
  type: LoadBalancer